[project]
org-name= "b7a_commons"
version= "0.1.0"

authors = ["info.rasika@gmail.com"]

repository = "https://github.com/ballerinalang/ballerina"

keywords = ["ballerina", "cli", "table", "uni-code", "text-table"]

license = ["MIT", "Apache-2.0"]

[dependencies]
